
### Create a new organization
POST /org/ HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
    "name": "Sample Organization",
    "email": "sample263@example.com",
    "zipcode": "12345678",
    "city": "Sample City",
    "state": "Sample State",
    "address": "123 Sample St",
    "number": "123",
    "complement": "Apt 456",
    "phone": "1234567890",
    "password": "123456"
}


### Authenticate user
POST /org/auth HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
    "email": "sample263@example.com",
    "password": "123456"
}


### Profile retrieval
GET /org/me HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE3YjkzMS00MDUxLTQ0MzEtODc4MS0xMzFiYjU4YjRjYzYiLCJpYXQiOjE3NjIzNzA4MDgsImV4cCI6MTc2MjM3MTQwOH0.M-nMePu4sFFGlRJBzkeJLqzLIxODMvs9cWQfuaqDFOQ

