
### Create a new organization
POST /org/ HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
    "name": "Sample Organization",
    "email": "sample263@example.com",
    "zipcode": "12345678",
    "city": "Sample City",
    "state": "Sample State",
    "address": "123 Sample St",
    "number": "123",
    "complement": "Apt 456",
    "phone": "1234567890",
    "password": "123456"
}


### Authenticate user
POST /org/auth HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
    "email": "sample263@example.com",
    "password": "123456"
}


### Profile retrieval
GET /org/me HTTP/1.1
Host: localhost:3333
Authorization: Bearer 


### Create a new pet to an organization
POST http://localhost:3333/pets
Authorization: Bearer 
Content-Type: application/json

{
    "species": "DOG",
    "name": "Rex", 
    "gender": "Macho",
    "color": "Marrom",
    "about": "Cachorro muito amigável e carinhoso",
    "age": "Adulto",
    "size": "Grande",
    "energyLevel": 4,
    "independenceLevel": 3,
    "environmentSize": "Amplo"
}

### Find pets by city
GET http://localhost:3333/pets?city=Sample%20City&species=DOG
Authorization: Bearer 


### Find pet by id
GET http://localhost:3333/pets/unique/c17386db-b5a1-4b5f-806f-009272aabfe6
Authorization: Bearer 

